# Generated by Django 4.0.8 on 2022-11-05 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Enter Blog Post Title', max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Enter Blog Post Slug')),
                ('published_date', models.DateTimeField(help_text='Blog Post Published Date', verbose_name='Published Date')),
                ('Last_modified_date', models.DateTimeField(help_text='Blog post Last Modified Date', verbose_name='Last Modified Date')),
                ('content_url', models.TextField(help_text='Enter Blog Post Content', verbose_name='Blog Post Body')),
                ('summary', models.TextField(help_text='Enter a brief description of the Blog Post', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
