# Generated by Django 4.0.8 on 2022-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Last_modified_date',
            field=models.DateTimeField(editable=False, help_text='Blog post Last Modified Date', verbose_name='Last Modified Date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(editable=False, help_text='Blog Post Published Date', verbose_name='Published Date'),
        ),
    ]
