# Generated by Django 4.0.8 on 2022-11-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blogpost_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Last_modified_date',
            field=models.DateTimeField(editable=False, help_text='Blog post Last Modified Date', null=True, verbose_name='Last Modified Date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(editable=False, help_text='Blog Post Published Date', null=True, verbose_name='Published Date'),
        ),
    ]
