# Generated by Django 4.0.8 on 2022-11-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blogpost_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Enter Blog Post Slug', unique=True),
        ),
    ]
